# ── Servidor ─────────────────────────────────────────────────────
server.port=8080

# ── MongoDB ───────────────────────────────────────────────────────
spring.data.mongodb.database=biblioteca_bd
spring.data.mongodb.uri=mongodb://localhost:27017

# ── JWT ───────────────────────────────────────────────────────────
jwt.secret=biblioteca_clave_super_secreta_2024_jwt_1234567890
jwt.expiration=3600000

# ── Logs ──────────────────────────────────────────────────────────
logging.level.org.springframework.security=DEBUG
logging.level.com.example.proyecto=DEBUG